# Generated by Django 5.1.6 on 2025-02-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_calculado', models.FloatField()),
                ('data', models.DateTimeField()),
                ('prefixo', models.CharField(max_length=50)),
                ('motorista', models.CharField(max_length=100)),
                ('cooperativa', models.CharField(max_length=100)),
                ('tipo_veiculo', models.CharField(max_length=50)),
                ('volume_carga', models.FloatField()),
            ],
        ),
    ]
