# Generated by Django 5.1.6 on 2025-03-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email_reset_password', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
